version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    
  student-registration-service:
    image: dtu-facade-entrypoint-service
    container_name: dtu-facade-entrypoint-service
    ports:
     - "8080:8080"
    
  student-id-service:
    image: dtu-merchant-service
    container_name: dtu-merchant-service

 
