version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    
  dtu-facade-entrypoint-service:
    image: dtu-facade-entrypoint
    container_name: dtu-facade-entrypoint-service
    ports:
     - "8080:8080"
    
  dtu-merchant-service:
    image: dtu-merchant
    container_name: dtu-merchant-service

  dtu-customer-service:
    image: dtu-customer
    container_name: dtu-customer-service

  dtu-moneytransfer-service:
    image: dtu-moneytransfer
    container_name: dtu-moneytransfer-service